MileStone1 Completed Awesome Book with  ES6
miftah1991/Awesomebooks-ES6 pull request #1
Opened 2022-02-14 19:03 UTC by miftah1991

This is Awesome book ES6  project and in this project, all the functions are separated as a module.

- Class for Book
- Class for Menu
- module for elements
- luxon package through npm for displaying time in the project
- Fix `linters`

2022-02-14 19:37 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @miftah1991,

Good job so far!
✔️ Nice modularizing of code
✔️ Use of ES6 syntax
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] **In your README documentation kindly add a section describing how users can set up and run the app locally**

- [ ] _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-14 19:37 UTC, TedLivist commented on modules/bookClass.js
> +      this.booksList.push(book);
- [ ] There seems to be an issue with your app. I am unable to add books. Kindly fix this.

  **SUGGESTION:** `this.booksList` is an undefined declaration in your app, hence the error. You can resolve this by defining `this.booksList = []` in the **constructor** method instead of having `static booksList = []` as you have on the top of the class

  ![mifta-add](https://user-images.githubusercontent.com/36542986/153932967-dd0f1419-207e-4de7-8e9d-2db66c594df7.jpg)

2022-02-14 19:37 UTC, TedLivist commented on modules/bookClass.js
> +    generateBooks() {
- [ ] Kindly refactor this function to use ES6 syntax (ie arrow function).

2022-02-14 19:37 UTC, TedLivist commented on modules/bookClass.js
> +  remove(index) {
- [ ] Kindly refactor to arrow function

2022-02-14 19:37 UTC, TedLivist commented on modules/bookClass.js
> +  addNewBook() {
- [ ] Kindly refactor to arrow function

2022-02-15 05:17 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @miftah1991,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-15 14:23 UTC, miftah1991 commented
@TedLivist  Thank you

2022-02-15 14:23 UTC, merged